### ISSUE TITLE
elasticsearch: port 9200 connectivity issue

### ISSUE THREAD

**Issue by aesophor** [dsnslab/NetworkSecurity#1]
Dear TAs,

## Here are what work for me so far
* **Ubuntu** - `ELK` is up and running (I can log into `kibana` with admin/admin)
* **Windows 10** - Installed `winlogbeat` and successfully started the service.

<br>

## The problem
No logs from `winlogbeat` were sent to elasticsearch (?)

![擷取(1)](https://user-images.githubusercontent.com/32998585/94587349-0a4bad80-02b5-11eb-9af5-8d482f6d857a.PNG)

<br>

## What I've tried
I've read [the official documentation](https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html#get-started-docker-tls) of elastic and, if I'm not mistaken, `winlogbeat` should send the logs via port 9200.

The official doc suggests that the user should run the following command to verify if the nodes are running:
```
$ curl -X GET "localhost:9200/_cat/nodes?v&pretty"
```

However, I received this output:
```
$ curl -X GET "localhost:9200/_cat/nodes?v&pretty"
curl: (52) Empty reply from server
```

Visiting this URL via a browser gives:

![scrot-2020-09-30_003329_828x747](https://user-images.githubusercontent.com/32998585/94587100-b2ad4200-02b4-11eb-8bb0-a65211c3ea15.png)

<br>

## My winlogbeat.yml
Using the following config, I can start the `winlogbeat` service successfully.
```
# =================================== Kibana ===================================
setup.kibana:
  # Kibana Host
  host: "192.168.131.137:5601"
```

```
# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["192.168.131.137:9200"]

  # Protocol - either `http` (default) or `https`.
  #protocol: "https"

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: "admin"
  password: "admin"
```

The problem is that there isn't any log from `winlogbeat` showing up in elasticsearch. 
Did I miss something? Thanks in advance! :pleading_face: :pleading_face:
