### ISSUE TITLE
Winlogbeat error connecting to Kibana

### ISSUE THREAD

**Issue by liitiisu** [dsnslab/NetworkSecurity#11]
**Dear TAs:**

# What I have done

- connect to the `kibana` on my virtual machine
![image](https://user-images.githubusercontent.com/55184427/96033967-6c023f00-0e93-11eb-9f47-a46b7be1bed2.png)

- According to the issues, I did `port forwarding`, but I'm not sure it is correct or not.

![image](https://user-images.githubusercontent.com/55184427/96034120-a370eb80-0e93-11eb-8711-85985bb92a35.png)

# Problems

As the title
![image](https://user-images.githubusercontent.com/55184427/96034206-c26f7d80-0e93-11eb-8db8-84c5cf3291b5.png)

I'm wondering that I didn't correct winlogbeat.yml as the right way, or my window just can't connect to my virtual box.
Thanks in advance. 😭

**Comment by dsnslab** [comment]
Your winlogbeat should connect to `127.0.0.1`.

**Comment by liitiisu** [comment]
- After editing the winlogbeat.yml, the situation seems to be better now.
![image](https://user-images.githubusercontent.com/55184427/96240819-f782e980-0fd3-11eb-9aec-1f10924f999d.png)
But it seems that nothing had been sent to my Ubuntu.
- At Windows, I can't ping 10.0.2.15.
- At the Kibana, I've increased the logstash index pattern.
![image](https://user-images.githubusercontent.com/55184427/96241422-b6d7a000-0fd4-11eb-8ee0-f66ca6c39770.png)
According to the warning, I've googled and deleted the winlogbeat* and do `.\winlogbeat setup --dashboards`, the winlogbeat* did appear.

**Comment by dsnslab** [comment]
Maybe you can provide **winlogbeat** debug message.
It seems winlogbeat fail to connect to logstash.

**Comment by liitiisu** [comment]
This is the screenshot of my clicking the warning.
![image](https://user-images.githubusercontent.com/55184427/96349560-07d5ba00-10e3-11eb-8a1d-0a41005c81fb.png)

**Comment by liitiisu** [comment]
I followed [https://www.elastic.co/guide/en/beats/winlogbeat/6.8/winlogbeat-installation.html](https://www.elastic.co/guide/en/beats/winlogbeat/6.8/winlogbeat-installation.html) step by step,  while testing the winlogbeat.yml, there are warnings.
![image](https://user-images.githubusercontent.com/55184427/96361597-b6b4dd00-1159-11eb-8a29-c0809bb1ca5d.png)
and, this is the warning at Kibana after I click it to see the full error.
![image](https://user-images.githubusercontent.com/55184427/96361587-a7ce2a80-1159-11eb-9fd6-f65c7cf2cdd3.png)
And at step three Step 3: Configure Winlogbeat to use Logstashedit, it tells that "For this configuration, you must[ load the index template into Elasticsearch manually](https://www.elastic.co/guide/en/beats/winlogbeat/6.8/winlogbeat-template.html#load-template-manually) because the options for auto loading the template are only available for the Elasticsearch output.", but it appears error like this.
![image](https://user-images.githubusercontent.com/55184427/96361695-79048400-115a-11eb-861f-42cd90c1e572.png)
I'm not sure where did I miss or wrong.

**Comment by dsnslab** [comment]
Maybe you can provide full winlogbeat.yml
It seems your setting is wrong.

**Comment by liitiisu** [comment]
Elasticsearch Output I comment out all of it.
```
setup.kibana:
  host: "127.0.0.1:5601"
  username: "admin"
  password: "admin"

output.logstash:
  hosts: `["127.0.0.1:5044"]
```

**Comment by jehoshuapratama** [comment]
Is this still an open problem? If yes, is the winlogbeat service running? If not please makesure that all the "elasticsearch" option in the configuration has been commented and provide your full configuration for troubleshooting.

**Comment by liitiisu** [comment]
Thanks for the advices, I’ll make sure and try it.

**Comment by liitiisu** [comment]
```
# ================================= Dashboards =================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here or by using the `setup` command.
setup.dashboards.enabled: true

# The URL from where to download the dashboards archive. By default this URL
# has a value which is computed based on the Beat name and version. For released
# versions, this URL points to the dashboard archive on the artifacts.elastic.co
# website.
#setup.dashboards.url:

# =================================== Kibana ===================================

# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup.kibana:

  # Kibana Host
  # Scheme and port can be left out and will be set to the default (http and 5601)
  # In case you specify and additional path, the scheme is required: http://localhost:5601/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
  host: "127.0.0.1:5601"
  username: "admin"
  password: "admin"

  # Kibana Space ID
  # ID of the Kibana Space into which the dashboards should be loaded. By default,
  # the Default Space will be used.
  #space.id:
# ------------------------------ Logstash Output -------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["127.0.0.1:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"
```

I think that these are all the codes that I have changed before.
And after running winlogbeat by `.\winlogbeat.exe -e`, it won't stop, I would like to ask is that normal or not.
