### ISSUE TITLE
Kibana can't find any index pattern like 'logstash*'

### ISSUE THREAD

**Issue by katelo731** [dsnslab/NetworkSecurity#12]
Dear TAs,

as title, as I apply the following settings:

### My 'winlogbeat.yml':
```
setup.kibana:
  host: "192.168.50.89:5601"
  username: "admin"
  password: "admin"
```
```
# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["192.168.50.89:5044"]
```

### Port forwarding:
![Capture5](https://user-images.githubusercontent.com/38788678/96270360-201fd900-0ffe-11eb-815f-58f4d5768ed0.JPG)

I can load into the dashboard successfully in Windows, but I can't find any index that contains 'logstash*' in Kibana and create it as an index pattern.

![Capture](https://user-images.githubusercontent.com/38788678/96271253-3e3a0900-0fff-11eb-94fb-5c960731b8ca.JPG)

Did I miss anything? 🥺
