### ISSUE TITLE
Question about Logstash Connection

### ISSUE THREAD

**Issue by chelseaxdxd** [dsnslab/NetworkSecurity#38]
Dear TAs,
I just finish my setting following the instruction you gave in previous issue question https://www.elastic.co/guide/en/beats/winlogbeat/7.11/winlogbeat-installation-configuration.html
Unfortunately, although I can successfully log into Kibana but there is no data related to Winlogbeat
## my Kibana now looks like this
I tried to set index pattern ```winlogbeat-* ``` as the instruction but there's no such data

![image](https://user-images.githubusercontent.com/43904738/111470853-3d023900-8763-11eb-8648-3e9483ed99c4.png)

## My winlogbeat.yml
```
# =================================== Kibana ===================================
setup.kibana:
  # Kibana Host
  host: "192.168.66.1:5601"
  username: "admin"
  password: "admin"
```
and I commented the Elasticsearch Output
```
#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["192.168.66.1:5044"]
```
## My question is
1. Do I need to do any command on the ubuntu side or I just need to open and sign in?
2.  Do I need to change any config and yml file in ubuntu side?
3. Since I also set the logging.files in winlogbeat.yml , I got the log and the error message is like this

![image](https://user-images.githubusercontent.com/43904738/111470788-2e1b8680-8763-11eb-8a9e-c990eaf38d08.png)

I cannot connent to Logstash but I don't know why 

I think I must missed something, sorry for bothering you🥺 🥺
